org: tonytangdeveloper
app: exchange-rate-api
service: exchange-rate-api
frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-3
  environment:
    FREE_CURRENCY_API_KEY: ${env:FREE_CURRENCY_API_KEY}

functions:
  convert:
    handler: src/handlers/convert.handler
    events:
      - httpApi:
          path: /convert
          method: post
